### ISSUE TITLE
Support "static" instances entries

### ISSUE THREAD

**Issue by elevran** [amalgam8/registry#20]
Currently registry requires valid and bounded TTL settings per instance. There are some use cases where customers want to register (often static) services so that they can be subjected to controller rules.
There are several ways to do that, including a new specialized catalog type or supporting "does not expire" entries (users are responsible for deregistering).

**Comment by elevran** [comment]
The following options were considered 

1. Tweak the maximum allowed TTL so very large TTL can be specified (e.g., 1 year)
1. Allow users to explicitly define "infinite" as TTL
1.  support a new read-only catalog, with services and instances based on a configuration file.

The first two options have several implications that complicate the solution:

- current registry replication relies on read-repair on heartbeating. It is not expected that we'll have any heartbeats for setrvice instances with large/infinite TTL.
- explicitly introducing infinite TTL in the API, may imply long term support. We believe this should be experimental as we better understand the requirement (e.g., injection of routes can be done through the service proxy directly, without involving the registry)
- since there is no persistent store, recovery from failure may require the user to re-register, which is likely not the expected behavior from a user perspective.

Thus, we're converging on the last option:

- introduce a new optional and experimental read-only catalog. 
- the catalog will be populated from a configuration file. If the file is not specified, the catalog will not be present. The file will be JSON based and contain an array of service instances in the same  format as used when POST'ing to `/instances`
- the catalog will re-read (periodically, on change event) the file's content and refresh the service instance definitions
- The file may be embedded into registry images (i.e., fixed, read only) or available on a shared volume., allowing the user to change it at runtime. This allows dynamic changes but is not user friendly. Should this feature prove useful, we'll evolve it to allow more user friendly dynamic changes.

**Comment by rshriram** [comment]
fixed by #23
