### ISSUE TITLE
Document Eureka clients support (including Ribbon, Spring Cloud)

### ISSUE THREAD

**Issue by ebullient** [amalgam8/registry#29]
Allow incremental adoption of a8 by allowing it to function as a drop-in replacement for Eureka, such that services built using Eureka clients (including Ribbon) do not have to be rewritten.

**Comment by rshriram** [comment]
The registry can already be used as a drop in replacement for Netflix Eureka. Its APIs are compatible with Ribbon as well. The usage model needs to be documented. 
And the trade-offs of this model (in ability to use the programmable sidecar when using Ribbon) needs to be documented as well. @elevran ??

**Comment by osowski** [comment]
@rshriram Is there an open issue for "*The usage model needs to be documented. *"?  If not, I will create one.  I do not see the usage documented anywhere, while it is mentioned as a "drop-in replacement" multiple times.

**Comment by zcahana** [comment]
As the Eureka support code is already in place, I'll retarget this issue at documenting its usage.
