### ISSUE TITLE
Prefix env vars with A8_

### ISSUE THREAD

**Issue by rshriram** [amalgam8/registry#30]
All env vars used by registry need to be prefixed with A8_ in order to avoid collision with user's environment variables.

**Comment by zcahana** [comment]
Registry-wise, it's a tiny change, but it'll break the examples and other environments where the Registry runs. When do want to do this? v0.3.0?

**Comment by rshriram** [comment]
In 0.2.. The example scripts can be updated. We are not having examples releases anymore.  we can release 0.2.1 of registry.
