### ISSUE TITLE
Default to trusted auth mode with 'info' log level

### ISSUE THREAD

**Issue by rshriram** [amalgam8/registry#31]
Pick a default auth mode (preferably trusted), to avoid having to supply command line arguments while starting the registry.

**Comment by zcahana** [comment]
The Registry's default auth mode (when no `--auth_mode` flag is provided) is "no auth", in which the client doesn't need to authenticate, and all clients share the same global namespace.

Perhaps this need to be more explicitly documented.

**Comment by rshriram** [comment]
But the controller expects to talk to registry using a token. And removing the token for registry communication would probably involve more changes in the controller than the one line change in registry's flag.go

**Comment by GregHanson** [comment]
The way I saw it, when running in `--auth_mode=trusted` the token is basically just an ID similar to how `local` is the ID for the sidecar in controller.

**Comment by rshriram** [comment]
Closing this. As the new plan is to default to global auth mode (which the registry already does), with A8_ environment vars, 'info' log level
